dist: trusty
sudo: required
language: cpp

env:
  - TRAVISFOAM_DIR=$TRAVIS_BUILD_DIR

before_install:
  - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
  - sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev" -y
  - sudo apt-get -qq update
  - sudo apt-get install openfoam-dev devscripts debhelper -y

before_script:
  - source /opt/openfoam-dev/etc/bashrc

script: debuild -i -us -uc -b
